### ISSUE TITLE
Possible to accept single quote around path when prompted for input path?

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/brat_to_cdli_conll_converter#3]

**Comment by greek-geek** [comment]
It'll accept single quotes with option -i. (For e.g. brat2conll -i 'data'). However, it doesn't seem to accept the single quotes from the prompt because '@click.option()', which is used to take the input parameter is internally checking if the given path exists and it gives an error if we use quotes

**Comment by epageperron** [comment]
Ok good to know, thanks for the clarification!
